Stewpra/R3Charge

index.html
I added an assets folder with a script.js and style.css files. I linked both to the index.html.
=> General File Structure

assets/script.js
Check the script.js file and see if there's an init function
=> Created init function and called it at the bottom of the page

assets/script.js
Created a function that will take any data and push to local storage.
=> Local Storage Data

index.html
I added a div container for the timer with id=timer. I also added a button element with id=button.
=> added timer container and button element

assets/script.js
added function handleClick. added click event listener that calls function handleClick
=> added function handleClick, added event listener

assets/script.js
tried to make a start timer function that can be passed a value of seconds that then countdown in the console.
=> 14 add a start timer function invoke it in the init function

assets/script.js, index.html
This PR is for this web page, if dayjs is working.
=> 6 add dayjs to project

index.html
- open html in live server
- see the battery display on centered on the page
=> 22 create battery display

assets/script.js, index.html
- open in live server
- you should see the battery indicator slowly go down, currently the total time and current time is hard coded at 30 seconds each, but can be adjusted by passing different parameters
=> Battery depletes as timer goes down

assets/script.js
Added fetch data function that can be passed a url and will return the dad joke/quote.
=> fetchData Function

assets/script.js
- open in live server
- open up the application tab in the dev tools
- look for a the localstorage value for startTime
=> 33 use dayjs to calculate the current time when the user starts the timer clicks the button

assets/script.js
- open in live server
- go to application tab
- check the value of 'startTime'
- the value should be a number with 10 digits, which is the unix time when the page was loaded
- try to reload the page and the time should update
=> Store unix time instead of full dayjs object

assets/script.js
- when opening the application, it should console log the unix time that's been saved in localStorage from last refresh
=> created function to get data from localStorage, added temp consolelog to test functionality

index.html
removed responsive breakpoints for buttons in header
=> removed responsive breakpoints for buttons in header

index.html
Changed title from doc to R3Charge
=> Change Title

index.html
I added an icon to the header buttons. I also put them into a container and placed a gap in between them to give space.
=> styled header buttons with icons and gap

assets/script.js
This PR is done for getting the total time.
=> 41 calculate hours minutes and seconds

assets/batteryDisplay.js, assets/script.js, assets/showText.js, assets/timer.js, index.html
- check the file structure
- you should see several new js files in the assets folder
=> pulled code to several other files, fixed some other small issues

assets/batteryDisplay.js, assets/script.js, assets/timer.js, index.html
- open the page using live server
- click the button to start the timer
- when the bar reaches the end, the height should decrease to match the curve of the battery
=> 52 update battery bars border radius

assets/batteryDisplay.js, assets/script.js, assets/showText.js, assets/timer.js, index.html
- Set up functions and adjusted functions to display the data from either api to the page
- Open in live server and you should see a joke displayed below the battery
=> 63 append quotejoke to display area

assets/script.js, assets/showText.js, assets/timer.js
- open in live server
- Start the timer and watch it tick down
- When it ticks down completely, it hides the battery and shows a quote
=> created a function for handling ending the work time.

assets/batteryDisplay.js, assets/script.js, assets/timer.js
I added the startRecharge function. When called it will work almost exactly like the start timer function except counts up. By calling the updateBattery function within the startRecharge function the battery will refill over the course of the break timer. The next steps will be to create a button and tie a click even to the calling of the function.
=> Added startRecharge function

assets/batteryDisplay.js
This PR is for new PR to merge the latest change.
=> git commit for new pull request

assets/script.js, assets/timer.js, index.html
- start a timer
- since the timer currently is only for 30 sec for testing purposes be quick
- refresh the page
- you should see the timer continue from where it left off, be it with a one second delay
=> the timer now starts if the user has an ongoing timer and has left page

assets/showText.js, assets/timer.js
Made it so the modal will pop up with a quote at the end of the work timer.
=> modal pop up after work timer

assets/script.js, assets/timer.js
Just used display none to get rid of buttons when the user shouldn't be able to press them.
=> Hidden buttons

assets/script.js, assets/timer.js, index.html
- press the start time button
- press the end time button
- you should see everything return to default
=> 102 handle end day function

assets/style.css, index.html
Used tailwind to hide recharge button when the page is loaded.
=> 98 link closing the modal to starting of the next timer

assets/showText.js, assets/timer.js, index.html
- the button at the bottom of the page and the one that shows the same modal, so display either one and you should see this
=> 105 adding content title to modal

assets/showText.js, index.html
=> fixed modal, reapplied styles to modal text

index.html
background shouldnt have two overlapped gradients anymore
=> fixed background gradient

index.html
Try different screen widths and check the battery size change
=> fixed battery display sizing for different screen widths

assets/timer.js, index.html
added descriptive text to the start button. 
added puncuation to the modal card text
added emoji to the start and recharge buttons.
=> 119 button labels

assets/timer.js
I added a the updateRemainingTimeDisplay to the recharge function to display the correct countdown.
=> 123 fix timer not updating past 1 second

assets/script.js, index.html
- added reveal button to html
- added variable for reveal timer button in script.js
- added event listener for reveal button
- added function for removing time from display
=> 127 adding button to show time
